name: Deployment of the application on koyeb
on:
  push:
    branches:
      - "*"
jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: getting the parameters of the SHA for the commit
        run: |
          echo ${{github.sha}} - commit sha that triggered this workflow
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.WIKI_PRECI_TOKEN }}"
      - name: Build the docker container
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: wiki-preci_${{ github.ref_name }}
          service-ports: "8000:http"
          service-routes: "/:8000"
          privileged: true
          skip-cache: true
