name: Deployment of the application on koyeb




on:
    push:
      branches:
        - '*'
jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@main
        with:
          api_token: "${{ secrets.WIKI_PRECI_TOKEN }}"

      - name: Build the docker container 
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: wiki-preci_${{ github.ref_name }}
          service-env: "PORT=8501"
          service-ports: "8501:http"
          service-routes: "/:8501"
          git-docker-dockerfile: Dockerfile.koyeb
          privileged: true
          skip-cache: true
  